version: "3.7"
services:
  localtunnel:
    image: server
    network_mode: host
    ports:
    - 3000
    command:
    - --port
    - "3000"
    - --domain
    - test.dsyer.com
  nginx:
    build: .
    network_mode: host
    depends_on:
    - localtunnel
    ports:
    - 80:80
    - 443:443
    volumes:
    - type: bind
      source: ./ssl
      target: /etc/nginx/ssl

